include /home/carlos/.local/include/cantera/Cantera.mak

#Parte de F90
FC= mpif90  -g -O0

#Parte de c++
CC=mpicc 
CXX=mpicxx 
RM=rm -f
CCFLAGS=-g
CPPFLAGS=$(CANTERA_INCLUDES)
LDFLAGS= # -fopenmp
LDLIBS=$(CANTERA_LIBS)

SRCScpp=cppwrapper.cpp
SRCSf90=fwrapper.f
OBJS=$(subst .cpp,.o,$(SRCScpp)) $(subst .f90,.o,$(SRCSf90))

all: test

test: $(OBJS)
	$(FC) $(LDFLAGS) -o test $(OBJS)  -lc -lstdc++ $(LDLIBS) 
	
%.o : %.f90
	$(F90) -c $<

%.o: %.cpp
	$(CXX) $(LDFLAGS) -c $< $(LDLIBS) $(CANTERA_INCLUDES)

clean:
	$(RM) $(OBJS)

dist-clean: clean
	$(RM) *~ 
